// Generated by しくみや — 2026-04-01T19:16:42.857Z
export const siteConfig = {
  name: "A",
  siteTitle: "A — Gallery",
  description: "Aのギャラリーサイト",
  url: "",
  lang: "ja",
  template: "neo-brutalist",

  colors: {
    primary: "#00e5ff",
    accent: "#d4a853",
    background: "#0a0a0f",
  },

  hero: {
    tagline: "Gallery",
    catchcopy: "Aの作品",
    subtitle: "Art Portfolio",
    description: "",
    backgroundImage: "/images/hero.webp",
    cta: {
      text: "作品を見る",
      href: "#gallery",
    },
  },

  gallery: {
    title: "GALLERY",
    subtitle: "作品ギャラリー",
    description: "",
    works: [
      { src: "/images/work_01.webp", title: "作品 01" },
      { src: "/images/work_02.webp", title: "作品 02" },
      { src: "/images/work_03.webp", title: "作品 03" },
    ],
    initialDisplay: 8,
  },

  about: {
    title: "ABOUT",
    subtitle: "アーティストについて",
    image: "/images/about.webp",
    paragraphs: [""],
    quote: "",
    tools: [],
  },

  contact: {
    title: "CONTACT",
    subtitle: "お問い合わせ・SNS",
    description: "お仕事のご依頼・コラボレーション・ご質問はお気軽にどうぞ。",
    email: "ryoya_ando@its-t.jp",
    social: [
    { label: "X (Twitter)", href: "https://x.com/kewpie_official?s=20" },
    ],
  },

  nav: [
    { label: "Gallery", href: "#gallery" },
    { label: "About", href: "#about" },
    { label: "Contact", href: "#contact" },
  ],

  footer: {
    credit: "Built with Next.js — Template by しくみや",
    copyright: `© ${new Date().getFullYear()} A. All rights reserved.`,
  },
};

export type SiteConfig = typeof siteConfig;
